#region Using directives
using System;
using UAManagedCore;
using OpcUa = UAManagedCore.OpcUa;
using FTOptix.HMIProject;
using FTOptix.NetLogic;
using FTOptix.Alarm;
using FTOptix.UI;
using FTOptix.NativeUI;
using FTOptix.Recipe;
using FTOptix.Store;
using FTOptix.ODBCStore;
using FTOptix.SQLiteStore;
using FTOptix.S7TiaProfinet;
using FTOptix.Retentivity;
using FTOptix.CoreBase;
using FTOptix.CommunicationDriver;
using FTOptix.Core;
#endregion

public class AssociazioneVarModelloAPLC : BaseNetLogic
{
    [ExportMethod]
    public void Method1()
    {
        /*------------------------------------------------
          variabili di modello 
        */
        
        //DB91
        var modello000 = Project.Current.GetVariable("Model/Drivers/DB91/DB91_CambioProduzione");
        var modello001 = Project.Current.GetVariable("Model/Drivers/DB91/DB91_TerminaProduzione");
        var modello002 = Project.Current.GetVariable("Model/Drivers/DB91/DB91_RiordinoProduzione");
        var modello003 = Project.Current.GetVariable("Model/Drivers/DB91/DB91_AckPezzoPersoPopup");
        var modello004 = Project.Current.GetVariable("Model/Drivers/DB91/DB91_AckInvioProgrammaPressa");
        var modello005 = Project.Current.GetVariable("Model/Drivers/DB91/DB91_AckProgrammaPressaInviatoOK");
        var modello006 = Project.Current.GetVariable("Model/Drivers/DB91/DB91_AckProgrammaPressaInviatoKO");
        var modello007 = Project.Current.GetVariable("Model/Drivers/DB91/DB91_AckReqLoadProgramOK");
        var modello008 = Project.Current.GetVariable("Model/Drivers/DB91/DB91_AckReqLoadProgramKO");
        var modello009 = Project.Current.GetVariable("Model/Drivers/DB91/DB91_Livebit");
        var modello010 = Project.Current.GetVariable("Model/Drivers/DB91/DB91_AbilitaSecomea");
        var modello011 = Project.Current.GetVariable("Model/Drivers/DB91/DB91_B_DoppioStile");
        var modello012 = Project.Current.GetVariable("Model/Drivers/DB91/DB91_B_PresenzaOffline");
        var modello013 = Project.Current.GetVariable("Model/Drivers/DB91/DB91_SceltaOPER_Spessore");
        var modello014 = Project.Current.GetVariable("Model/Drivers/DB91/DB91_SceltaTipoMisuraSpessore");
        var modello015 = Project.Current.GetVariable("Model/Drivers/DB91/Ricetta/Product_ID");
        var modello016 = Project.Current.GetVariable("Model/Drivers/DB91/Ricetta/ProgrammaRobot");
        var modello017 = Project.Current.GetVariable("Model/Drivers/DB91/Ricetta/PrgPressa");
        var modello018 = Project.Current.GetVariable("Model/Drivers/DB91/Ricetta/NumPrgPressa");
        var modello019 = Project.Current.GetVariable("Model/Drivers/DB91/Ricetta/QtaRichiesta");
        var modello020 = Project.Current.GetVariable("Model/Drivers/DB91/Ricetta/QtaRiordino");
        var modello021 = Project.Current.GetVariable("Model/Drivers/DB91/Ricetta/CodArticolo");

        // DB92
        var modello050 = Project.Current.GetVariable("Model/Drivers/DB92/DB92_ODP");
        var modello051 = Project.Current.GetVariable("Model/Drivers/DB92/DB92_PrgRobot");
        var modello052 = Project.Current.GetVariable("Model/Drivers/DB92/DB92_PrgPressa");
        var modello053 = Project.Current.GetVariable("Model/Drivers/DB92/DB92_NumPrgPressa");
        var modello054 = Project.Current.GetVariable("Model/Drivers/DB92/DB92_QtaRichiesta");
        var modello055 = Project.Current.GetVariable("Model/Drivers/DB92/DB92_QtaRiordino");
        var modello056 = Project.Current.GetVariable("Model/Drivers/DB92/DB92_CodArticolo");
        var modello057 = Project.Current.GetVariable("Model/Drivers/DB92/DB92_CambioProduzioneOK");
        var modello058 = Project.Current.GetVariable("Model/Drivers/DB92/DB92_CambioProduzioneKO");
        var modello059 = Project.Current.GetVariable("Model/Drivers/DB92/DB92_AckTerminaProduzione");
        var modello060 = Project.Current.GetVariable("Model/Drivers/DB92/DB92_ProduzioneInCorso");
        var modello061 = Project.Current.GetVariable("Model/Drivers/DB92/DB92_InviaProgrammaAPressa");
        var modello062 = Project.Current.GetVariable("Model/Drivers/DB92/DB92_Livebit");
        var modello063 = Project.Current.GetVariable("Model/Drivers/DB92/DB92_PezziDepositati");
        var modello064 = Project.Current.GetVariable("Model/Drivers/DB92/DB92_PezziScarti");

        // Allarmi/Warning
        var modello080 = Project.Current.GetVariable("Model/Alarms/Alm1");
        var modello081 = Project.Current.GetVariable("Model/Alarms/Alm2");
        var modello082 = Project.Current.GetVariable("Model/Alarms/Alm3");
        var modello083 = Project.Current.GetVariable("Model/Alarms/Alm4");
        var modello084 = Project.Current.GetVariable("Model/Alarms/Alm5");
        var modello085 = Project.Current.GetVariable("Model/Alarms/Alm6");
        var modello086 = Project.Current.GetVariable("Model/Alarms/Alm7");
        var modello087 = Project.Current.GetVariable("Model/Alarms/Alm8");
        var modello088 = Project.Current.GetVariable("Model/Alarms/Alm9");
        var modello089 = Project.Current.GetVariable("Model/Alarms/Alm10");
        var modello090 = Project.Current.GetVariable("Model/Alarms/Alm11");
        var modello091 = Project.Current.GetVariable("Model/Alarms/Alm12");
        var modello092 = Project.Current.GetVariable("Model/Alarms/Alm13");
        var modello093 = Project.Current.GetVariable("Model/Alarms/Alm14");
        var modello094 = Project.Current.GetVariable("Model/Alarms/Alm15");
        var modello095 = Project.Current.GetVariable("Model/Alarms/Alm16");
        var modello096 = Project.Current.GetVariable("Model/Alarms/Alm17");
        var modello097 = Project.Current.GetVariable("Model/Alarms/Alm18");
        var modello098 = Project.Current.GetVariable("Model/Alarms/Alm19");
        var modello099 = Project.Current.GetVariable("Model/Alarms/Alm20");
        var modello100 = Project.Current.GetVariable("Model/Alarms/Alm21");
        var modello101 = Project.Current.GetVariable("Model/Alarms/Alm22");
        var modello102 = Project.Current.GetVariable("Model/Alarms/Alm23");
        var modello103 = Project.Current.GetVariable("Model/Alarms/Alm24");
        var modello104 = Project.Current.GetVariable("Model/Alarms/Alm25");
        var modello105 = Project.Current.GetVariable("Model/Alarms/Alm26");
        var modello106 = Project.Current.GetVariable("Model/Alarms/Alm27");
        var modello107 = Project.Current.GetVariable("Model/Alarms/Alm28");
        var modello108 = Project.Current.GetVariable("Model/Alarms/Alm29");
        var modello109 = Project.Current.GetVariable("Model/Alarms/Alm30");
        var modello110 = Project.Current.GetVariable("Model/Alarms/Alm31");
        var modello111 = Project.Current.GetVariable("Model/Alarms/Alm32");
        var modello112 = Project.Current.GetVariable("Model/Alarms/Wrn1");
        var modello113 = Project.Current.GetVariable("Model/Alarms/Wrn2");
        var modello114 = Project.Current.GetVariable("Model/Alarms/Wrn3");
        var modello115 = Project.Current.GetVariable("Model/Alarms/Wrn4");
        var modello116 = Project.Current.GetVariable("Model/Alarms/Wrn5");
        var modello117 = Project.Current.GetVariable("Model/Alarms/Wrn6");
        var modello118 = Project.Current.GetVariable("Model/Alarms/Wrn7");
        var modello119 = Project.Current.GetVariable("Model/Alarms/Wrn8");
        var modello120 = Project.Current.GetVariable("Model/Alarms/Wrn9");
        var modello121 = Project.Current.GetVariable("Model/Alarms/Wrn10");
        var modello122 = Project.Current.GetVariable("Model/Alarms/Wrn11");
        var modello123 = Project.Current.GetVariable("Model/Alarms/Wrn12");
        var modello124 = Project.Current.GetVariable("Model/Alarms/Wrn13");
        var modello125 = Project.Current.GetVariable("Model/Alarms/Wrn14");
        var modello126 = Project.Current.GetVariable("Model/Alarms/Wrn15");
        var modello127 = Project.Current.GetVariable("Model/Alarms/Wrn16");
        var modello128 = Project.Current.GetVariable("Model/Alarms/Wrn17");
        var modello129 = Project.Current.GetVariable("Model/Alarms/Wrn18");
        var modello130 = Project.Current.GetVariable("Model/Alarms/Wrn19");
        var modello131 = Project.Current.GetVariable("Model/Alarms/Wrn20");
        var modello132 = Project.Current.GetVariable("Model/Alarms/Wrn21");
        var modello133 = Project.Current.GetVariable("Model/Alarms/Wrn22");
        var modello134 = Project.Current.GetVariable("Model/Alarms/Wrn23");
        var modello135 = Project.Current.GetVariable("Model/Alarms/Wrn24");
        var modello136 = Project.Current.GetVariable("Model/Alarms/Wrn25");
        var modello137 = Project.Current.GetVariable("Model/Alarms/Wrn26");
        var modello138 = Project.Current.GetVariable("Model/Alarms/Wrn27");
        var modello139 = Project.Current.GetVariable("Model/Alarms/Wrn28");
        var modello140 = Project.Current.GetVariable("Model/Alarms/Wrn29");
        var modello141 = Project.Current.GetVariable("Model/Alarms/Wrn30");
        var modello142 = Project.Current.GetVariable("Model/Alarms/Wrn31");
        var modello143 = Project.Current.GetVariable("Model/Alarms/Wrn32");
        
        /*------------------------------------------------
           variabili di PLC
        */
        
        // DB91
        var varPLC000 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/CambioProduzione");
        var varPLC001 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/TerminaProduzione");
        var varPLC002 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/RiordinoProduzione");
        var varPLC003 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/AckPezzoPersoPopup");
        var varPLC004 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/AckInvioProgrammaPressa");
        var varPLC005 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/AckProgrammaPressaInviatoOK");
        var varPLC006 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/AckProgrammaPressaInviatoKO");
        var varPLC007 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/AckReqLoadProgramOK");
        var varPLC008 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/AckReqLoadProgramKO");
        var varPLC009 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/Livebit");
        var varPLC010 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/AbilitaSecomea");
        var varPLC011 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/B_DoppioStile");
        var varPLC012 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/B_PresenzaOffline");
        var varPLC013 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/SceltaOPER_Spessore");
        var varPLC014 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/SceltaTipoMisuraSpessore");
        var varPLC015 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/NuovaRicetta/ODP");
        var varPLC016 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/NuovaRicetta/PrgRobot");
        var varPLC017 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/NuovaRicetta/PrgPressa");
        var varPLC018 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/NuovaRicetta/NumPrgPressa");
        var varPLC019 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/NuovaRicetta/QtaRichiesta");
        var varPLC020 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/NuovaRicetta/QtaRiordino");
        var varPLC021 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB91-HMItoPLC/NuovaRicetta/CodArticolo");  
        
        // DB92
        var varPLC050 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB92-PLCtoHMI/RicettaInCorso/ODP");
        var varPLC051 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB92-PLCtoHMI/RicettaInCorso/PrgRobot");
        var varPLC052 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB92-PLCtoHMI/RicettaInCorso/PrgPressa");
        var varPLC053 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB92-PLCtoHMI/RicettaInCorso/NumPrgPressa");
        var varPLC054 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB92-PLCtoHMI/RicettaInCorso/QtaRichiesta");
        var varPLC055 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB92-PLCtoHMI/RicettaInCorso/QtaRiordino");
        var varPLC056 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB92-PLCtoHMI/RicettaInCorso/CodArticolo");
        var varPLC057 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB92-PLCtoHMI/CambioProduzioneOK");
        var varPLC058 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB92-PLCtoHMI/CambioProduzioneKO");
        var varPLC059 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB92-PLCtoHMI/AckTerminaProduzione");
        var varPLC060 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB92-PLCtoHMI/ProduzioneInCorso");
        var varPLC061 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB92-PLCtoHMI/InviaProgrammaAPressa");
        var varPLC062 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB92-PLCtoHMI/Livebit");
        var varPLC063 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB92-PLCtoHMI/PezziDepositati");
        var varPLC064 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Standard/90-HMI/DB92-PLCtoHMI/PezziScarti");
        
        // Allarmi/Warning
        var varPLC080 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_1");
        var varPLC081 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_2");
        var varPLC082 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_3");
        var varPLC083 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_4");
        var varPLC084 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_5");
        var varPLC085 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_6");
        var varPLC086 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_7");
        var varPLC087 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_8");
        var varPLC088 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_9");
        var varPLC089 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_10");
        var varPLC090 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_11");
        var varPLC091 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_12");
        var varPLC092 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_13");
        var varPLC093 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_14");
        var varPLC094 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_15");
        var varPLC095 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_16");
        var varPLC096 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_17");
        var varPLC097 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_18");
        var varPLC098 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_19");
        var varPLC099 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_20");
        var varPLC100 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_21");
        var varPLC101 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_22");
        var varPLC102 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_23");
        var varPLC103 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_24");
        var varPLC104 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_25");
        var varPLC105 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_26");
        var varPLC106 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_27");
        var varPLC107 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_28");
        var varPLC108 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_29");
        var varPLC109 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_30");
        var varPLC110 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_31");
        var varPLC111 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Alm_32");
        var varPLC112 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_1");
        var varPLC113 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_2");
        var varPLC114 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_3");
        var varPLC115 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_4");
        var varPLC116 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_5");
        var varPLC117 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_6");
        var varPLC118 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_7");
        var varPLC119 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_8");
        var varPLC120 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_9");
        var varPLC121 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_10");
        var varPLC122 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_11");
        var varPLC123 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_12");
        var varPLC124 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_13");
        var varPLC125 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_14");
        var varPLC126 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_15");
        var varPLC127 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_16");
        var varPLC128 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_17");
        var varPLC129 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_18");
        var varPLC130 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_19");
        var varPLC131 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_20");
        var varPLC132 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_21");
        var varPLC133 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_22");
        var varPLC134 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_23");
        var varPLC135 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_24");
        var varPLC136 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_25");
        var varPLC137 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_26");
        var varPLC138 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_27");
        var varPLC139 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_28");
        var varPLC140 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_29");
        var varPLC141 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_30");
        var varPLC142 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_31");
        var varPLC143 = Project.Current.GetVariable("CommDrivers/S7TIAPROFINETDriver3/S7TIAPROFINETStation1/Tags/PRG10021/Supporto/DB15_All_Wrn/w_Wrn_32");

        /*------------------------------------------------
           dinamicLink per Optix
        */
        modello000.SetDynamicLink(varPLC000, DynamicLinkMode.ReadWrite);
        modello001.SetDynamicLink(varPLC001, DynamicLinkMode.ReadWrite);
        modello002.SetDynamicLink(varPLC002, DynamicLinkMode.ReadWrite);
        modello003.SetDynamicLink(varPLC003, DynamicLinkMode.ReadWrite);
        modello004.SetDynamicLink(varPLC004, DynamicLinkMode.ReadWrite);
        modello005.SetDynamicLink(varPLC005, DynamicLinkMode.ReadWrite);
        modello006.SetDynamicLink(varPLC006, DynamicLinkMode.ReadWrite);
        modello007.SetDynamicLink(varPLC007, DynamicLinkMode.ReadWrite);
        modello008.SetDynamicLink(varPLC008, DynamicLinkMode.ReadWrite);
        modello009.SetDynamicLink(varPLC009, DynamicLinkMode.ReadWrite);
        modello010.SetDynamicLink(varPLC010, DynamicLinkMode.ReadWrite);
        modello011.SetDynamicLink(varPLC011, DynamicLinkMode.ReadWrite);
        modello012.SetDynamicLink(varPLC012, DynamicLinkMode.ReadWrite);
        modello013.SetDynamicLink(varPLC013, DynamicLinkMode.ReadWrite);
        modello014.SetDynamicLink(varPLC014, DynamicLinkMode.ReadWrite);
        modello015.SetDynamicLink(varPLC015, DynamicLinkMode.ReadWrite);
        modello016.SetDynamicLink(varPLC016, DynamicLinkMode.ReadWrite);
        modello017.SetDynamicLink(varPLC017, DynamicLinkMode.ReadWrite);
        modello018.SetDynamicLink(varPLC018, DynamicLinkMode.ReadWrite);
        modello019.SetDynamicLink(varPLC019, DynamicLinkMode.ReadWrite);
        modello020.SetDynamicLink(varPLC020, DynamicLinkMode.ReadWrite);
        modello021.SetDynamicLink(varPLC021, DynamicLinkMode.ReadWrite);
        modello050.SetDynamicLink(varPLC050, DynamicLinkMode.ReadWrite);
        modello051.SetDynamicLink(varPLC051, DynamicLinkMode.ReadWrite);
        modello052.SetDynamicLink(varPLC052, DynamicLinkMode.ReadWrite);
        modello053.SetDynamicLink(varPLC053, DynamicLinkMode.ReadWrite);
        modello054.SetDynamicLink(varPLC054, DynamicLinkMode.ReadWrite);
        modello055.SetDynamicLink(varPLC055, DynamicLinkMode.ReadWrite);
        modello056.SetDynamicLink(varPLC056, DynamicLinkMode.ReadWrite);
        modello057.SetDynamicLink(varPLC057, DynamicLinkMode.ReadWrite);
        modello058.SetDynamicLink(varPLC058, DynamicLinkMode.ReadWrite);
        modello059.SetDynamicLink(varPLC059, DynamicLinkMode.ReadWrite);
        modello060.SetDynamicLink(varPLC060, DynamicLinkMode.ReadWrite);
        modello061.SetDynamicLink(varPLC061, DynamicLinkMode.ReadWrite);
        modello062.SetDynamicLink(varPLC062, DynamicLinkMode.ReadWrite);
        modello063.SetDynamicLink(varPLC063, DynamicLinkMode.ReadWrite);
        modello064.SetDynamicLink(varPLC064, DynamicLinkMode.ReadWrite);
        modello080.SetDynamicLink(varPLC080, DynamicLinkMode.ReadWrite);
        modello081.SetDynamicLink(varPLC081, DynamicLinkMode.ReadWrite);
        modello082.SetDynamicLink(varPLC082, DynamicLinkMode.ReadWrite);
        modello083.SetDynamicLink(varPLC083, DynamicLinkMode.ReadWrite);
        modello084.SetDynamicLink(varPLC084, DynamicLinkMode.ReadWrite);
        modello085.SetDynamicLink(varPLC085, DynamicLinkMode.ReadWrite);
        modello086.SetDynamicLink(varPLC086, DynamicLinkMode.ReadWrite);
        modello087.SetDynamicLink(varPLC087, DynamicLinkMode.ReadWrite);
        modello088.SetDynamicLink(varPLC088, DynamicLinkMode.ReadWrite);
        modello089.SetDynamicLink(varPLC089, DynamicLinkMode.ReadWrite);
        modello090.SetDynamicLink(varPLC090, DynamicLinkMode.ReadWrite);
        modello091.SetDynamicLink(varPLC091, DynamicLinkMode.ReadWrite);
        modello092.SetDynamicLink(varPLC092, DynamicLinkMode.ReadWrite);
        modello093.SetDynamicLink(varPLC093, DynamicLinkMode.ReadWrite);
        modello094.SetDynamicLink(varPLC094, DynamicLinkMode.ReadWrite);
        modello095.SetDynamicLink(varPLC095, DynamicLinkMode.ReadWrite);
        modello096.SetDynamicLink(varPLC096, DynamicLinkMode.ReadWrite);
        modello097.SetDynamicLink(varPLC097, DynamicLinkMode.ReadWrite);
        modello098.SetDynamicLink(varPLC098, DynamicLinkMode.ReadWrite);
        modello099.SetDynamicLink(varPLC099, DynamicLinkMode.ReadWrite);
        modello100.SetDynamicLink(varPLC100, DynamicLinkMode.ReadWrite);
        modello101.SetDynamicLink(varPLC101, DynamicLinkMode.ReadWrite);
        modello102.SetDynamicLink(varPLC102, DynamicLinkMode.ReadWrite);
        modello103.SetDynamicLink(varPLC103, DynamicLinkMode.ReadWrite);
        modello104.SetDynamicLink(varPLC104, DynamicLinkMode.ReadWrite);
        modello105.SetDynamicLink(varPLC105, DynamicLinkMode.ReadWrite);
        modello106.SetDynamicLink(varPLC106, DynamicLinkMode.ReadWrite);
        modello107.SetDynamicLink(varPLC107, DynamicLinkMode.ReadWrite);
        modello108.SetDynamicLink(varPLC108, DynamicLinkMode.ReadWrite);
        modello109.SetDynamicLink(varPLC109, DynamicLinkMode.ReadWrite);
        modello110.SetDynamicLink(varPLC110, DynamicLinkMode.ReadWrite);
        modello111.SetDynamicLink(varPLC111, DynamicLinkMode.ReadWrite);
        modello112.SetDynamicLink(varPLC112, DynamicLinkMode.ReadWrite);
        modello113.SetDynamicLink(varPLC113, DynamicLinkMode.ReadWrite);
        modello114.SetDynamicLink(varPLC114, DynamicLinkMode.ReadWrite);
        modello115.SetDynamicLink(varPLC115, DynamicLinkMode.ReadWrite);
        modello116.SetDynamicLink(varPLC116, DynamicLinkMode.ReadWrite);
        modello117.SetDynamicLink(varPLC117, DynamicLinkMode.ReadWrite);
        modello118.SetDynamicLink(varPLC118, DynamicLinkMode.ReadWrite);
        modello119.SetDynamicLink(varPLC119, DynamicLinkMode.ReadWrite);
        modello120.SetDynamicLink(varPLC120, DynamicLinkMode.ReadWrite);
        modello121.SetDynamicLink(varPLC121, DynamicLinkMode.ReadWrite);
        modello122.SetDynamicLink(varPLC122, DynamicLinkMode.ReadWrite);
        modello123.SetDynamicLink(varPLC123, DynamicLinkMode.ReadWrite);
        modello124.SetDynamicLink(varPLC124, DynamicLinkMode.ReadWrite);
        modello125.SetDynamicLink(varPLC125, DynamicLinkMode.ReadWrite);
        modello126.SetDynamicLink(varPLC126, DynamicLinkMode.ReadWrite);
        modello127.SetDynamicLink(varPLC127, DynamicLinkMode.ReadWrite);
        modello128.SetDynamicLink(varPLC128, DynamicLinkMode.ReadWrite);
        modello129.SetDynamicLink(varPLC129, DynamicLinkMode.ReadWrite);
        modello130.SetDynamicLink(varPLC130, DynamicLinkMode.ReadWrite);
        modello131.SetDynamicLink(varPLC131, DynamicLinkMode.ReadWrite);
        modello132.SetDynamicLink(varPLC132, DynamicLinkMode.ReadWrite);
        modello133.SetDynamicLink(varPLC133, DynamicLinkMode.ReadWrite);
        modello134.SetDynamicLink(varPLC134, DynamicLinkMode.ReadWrite);
        modello135.SetDynamicLink(varPLC135, DynamicLinkMode.ReadWrite);
        modello136.SetDynamicLink(varPLC136, DynamicLinkMode.ReadWrite);
        modello137.SetDynamicLink(varPLC137, DynamicLinkMode.ReadWrite);
        modello138.SetDynamicLink(varPLC138, DynamicLinkMode.ReadWrite);
        modello139.SetDynamicLink(varPLC139, DynamicLinkMode.ReadWrite);
        modello140.SetDynamicLink(varPLC140, DynamicLinkMode.ReadWrite);
        modello141.SetDynamicLink(varPLC141, DynamicLinkMode.ReadWrite);
        modello142.SetDynamicLink(varPLC142, DynamicLinkMode.ReadWrite);
        modello143.SetDynamicLink(varPLC143, DynamicLinkMode.ReadWrite);
    }
}
