Name: Produzione
Type: FolderType
Children:
- Name: NuovaProduzione
  Id: g=3c814e6e698d389a0e42f4300f4f94cf
  Type: BaseObjectType
  Children:
  - Name: Odp
    Type: BaseDataVariableType
    DataType: String
  - Name: NomeArticolo
    Type: BaseDataVariableType
    DataType: String
  - Name: Quantità
    Type: BaseDataVariableType
    DataType: Int32
    Value: 1
- Name: rowIdSelected
  Id: g=15aaff7cec2db47876fbb03b9dd0ecb8
  Type: BaseDataVariableType
  DataType: Int64
- Name: ButtonProduzioneEnabled
  Type: BaseObjectType
  Children:
  - Name: AvviaEnabled
    Type: BaseDataVariableType
    DataType: Boolean
  - Name: TerminaEnabled
    Type: BaseDataVariableType
    DataType: Boolean
  - Name: EliminaEnabled
    Type: BaseDataVariableType
    DataType: Boolean
- Name: FiltroProduzione
  Type: BaseObjectType
  Children:
  - Name: TextFilter
    Type: BaseDataVariableType
    DataType: String
  - Name: FilterActive
    Id: g=de66cd134b3e33b4d9ced9a7e5eccf1d
    Type: BaseDataVariableType
    DataType: Boolean
- Name: QueryProduzione
  Type: BaseDataVariableType
  DataType: String
  Value: "0"
- Name: pr_ButtonTerminaSelected
  Id: g=71fcbfc6dd117edefa4d264a12ac438e
  Type: BaseDataVariableType
  DataType: Boolean
- Name: OdlStart
  Type: BaseDataVariableType
  DataType: Int64
- Name: ap_start
  Type: BaseDataVariableType
  DataType: Boolean
- Name: ResetProduction
  Type: BaseDataVariableType
  DataType: Boolean
- Name: ProduzioneInCorso
  Type: BaseDataVariableType
  DataType: Boolean
- Name: DelButton
  Id: g=b9185d76a8ecec6b98bcd1dae264e64e
  Type: BaseDataVariableType
  DataType: Boolean
- Name: ClockLogic_DateTimeCreate_
  Type: NetLogic
  WriteMask: BrowseName|DataType|Description|DisplayName|MinimumSamplingInterval|UserAccessLevel
  Children:
  - Name: Time
    Type: BaseDataVariableType
    DataType: DateTime
    Children:
    - Name: Year
      Type: BaseDataVariableType
      DataType: Int32
    - Name: Month
      Type: BaseDataVariableType
      DataType: Int32
    - Name: Day
      Type: BaseDataVariableType
      DataType: Int32
    - Name: Hour
      Type: BaseDataVariableType
      DataType: Int32
    - Name: Minute
      Type: BaseDataVariableType
      DataType: Int32
    - Name: Second
      Type: BaseDataVariableType
      DataType: Int32
  - Name: UTCTime
    Type: BaseDataVariableType
    DataType: DateTime
    Children:
    - Name: Year
      Type: BaseDataVariableType
      DataType: Int32
    - Name: Month
      Type: BaseDataVariableType
      DataType: Int32
    - Name: Day
      Type: BaseDataVariableType
      DataType: Int32
    - Name: Hour
      Type: BaseDataVariableType
      DataType: Int32
    - Name: Minute
      Type: BaseDataVariableType
      DataType: Int32
    - Name: Second
      Type: BaseDataVariableType
      DataType: Int32
  - Name: ns=4;LibraryReference
    Type: ObjectLibraryReference
    DataType: ObjectLibraryReferenceDataType
    Value: 
     {
      "TypeId": {
       "Id": 72,
       "Namespace": 4
      },
      "Body": {
       "libraryGuid": "f0701375ee41467993d632db6a8fdaa5",
       "objectGuid": "9996e8e9dc11a5c3e3631c6fb9425d2d",
       "objectVersion": 1,
       "highestIgnoredVersion": 0
      }
     }
